//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolsSys.BL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Attachments = new HashSet<Attachment>();
        }
    
        public int StudentId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public int GradeId { get; set; }
        public int ClassId { get; set; }
        public System.DateTime BirthDate { get; set; }
        public int GenderTypeId { get; set; }
        public Nullable<decimal> PickupLongitude { get; set; }
        public Nullable<decimal> PickupLatitude { get; set; }
        public Nullable<decimal> DropOffLongitude { get; set; }
        public Nullable<decimal> DropOffLatitude { get; set; }
        public Nullable<bool> SubscribedToBus { get; set; }
        public string MobileNumber { get; set; }
        public string Email { get; set; }
        public string ProfilePicturePath { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attachment> Attachments { get; set; }
        public virtual Class Class { get; set; }
        public virtual Grade Grade { get; set; }
    }
}
